subject = """
Тема книги - практическое руководство для специалистов в нефтепереработке по поиску задач для проектов машинного обучения и их успешного решения.
Основная цель книги - сделать из читателя квалифицированного заказчика проекта по машинному обучению. Она дает понимание как искать задачи для искусственного интеллекта, как внедрять такие проекты в нефтепереработку
и какие шаги следует сделать для получения успешного рзультата.
Также она включает основные риски и подводные камни в таких проектах и способы их избежать.
Также книга дает развернутое представление о том как оценивать эффективность проектов на основе машинного обучения и искусственного интеллекта.
Она включает в себя основные сведения по машинному обучению и искусственному интеллекту. Также книга включает в себя множество практических советов и подходов для поиска задач,
подходов к написанию технического задания, приемки результатов и внедрения технологий машинного обучения и искуственного интеллекта в нефтепереработку.
Книга включает вопросы на самопроверку и список конкретных рекомендуемых действий для читателя после каждой главы.
Также книга включает приложения содержащее основные термины из машинного обучения и искусственного интеллекта а также шаблон технического задания на проект на основе машинного обучения
"""
profile = """
Эта книга представляет из себя практическое руководство для специалистов нефтепереработки по выбору задачи, формированию корректного и всестороннего технического задания, контроля хода проекта, приемки результатов, внедрения и оценки экономического эффекта.
Основная аудитория книги - специалисты нефтепереработки, от операторов и начальников установок до руководителей нефтеперерабатывающих производств. Читатели - не специалисты в области искусственного интеллекта и машинного обучения. Они специалисты в области нефтепереработки.
Она дает все необходимые знания для квалифицированного заказчика проектов на основе машинного обучения. Книга включает в себя основные сведения об алгоритмах искусственного интеллекта, подходов к решению различных задач и способов оценки качества полученного результата.
Также книга показывает основные проблемы при реализации таких проектов - данные, интеграция, неуспешные внедрения и т.д., и предлагает способы решения этих проблем.
Книга дает детальный, пошаговый план поиска задачи, формирования технического задания, эффективной и прозрачной коммуникации со специалистами по искусственному интеллекту, приемке результата, оценки качества моделей и внедрения проекта в производство.
Она содержит объяснения основных терминов искусственного интеллекта для эффективной коммуникации со специалистами по машинному обучению.
Также она содержит в каждой главе список конкретных шагов, которые может сделать читатель после прочтения главы а также список вопросов для самопроверки.
В приложениях к книге содержится шаблон технического задания на проект машинного обучения, который по мере прочтения книги читатель может успешно заполнить.
Также в приложениях к книге содержится список интересных и полезных терминов и ссылок для читателя который хочет глубже погрузится в тему.
"""
style = "Практическое руководство-Компьютерные технологии-Искусственный интеллект"
genre = "Научная литература: Искусственный интеллект и машинное обучение"

[title_ideas]
load_title = false
title = ""
prompt = """
Ваша задача - придумать подходящее название для книги на указанную тему.
Пожалуйста, укажите название, и только название!
Название должно соответствовать тематике книги.
Название должно соответствовать жанру книги.
Название должно соответствовать стилю книги.

Тема книги: {subject}
Жанр книги: {genre}
Стиль: {style}

Описание книги: {profile}

Название:
"""

[framework]
load_framework = false
helper_prompt = """
Составьте список характеристик, которые помогают написать научно-популярную книгу.

Список характеристик:
"""
prompt = """
Ваша задача - создать структуру для научно-популярного практического руководства (книги).
Верните структуру и только структуру!
Опишите всю структуру таким образом, чтобы она служила дорожной картой для книги
, помогала систематизировать мысли, связно излагать аргументы и направлять читателя
в изучении центральных тем и концепций книги.
Вам будут предоставлены сведения о теме, жанре, стиле, названии и профиле книги.
Структура должна соответствовать профилю книги.
Структура должна соответствовать жанру книги.
Структура должна соответствовать стилю книги.

Учитывайте следующие атрибуты, чтобы создать всеобъемлющую структуру:
{features}

тема: {subject}
жанр: {genre}
стиль: {style}
название: {title}
Описание книги: {profile}

Стуктура:
"""

[chapters]
load_chapters = false
prompt = """
Ваша задача - создать список глав для книги.
Пожалуйста, создайте список глав и только список глав!
Вам будет предоставлена информация о теме, жанре, стиле, названии, профиле и структуре книги.
Пожалуйста, составьте список глав, который хорошо описывает предлагаемую структуру.
Список глав должен соответствовать структуре.
Список глав должен соответствовать жанру книги.
Список глав должен соответствовать стилю книги.
Чтобы сформировать список глав, пожалуйста, следуйте следующему шаблону:

Введение: [описание введения]
Глава 1: [описание главы 1]
...
Заключение: [описание послесловия]

Пожалуйста, убедитесь, что в разделах "Введение` и `Заключение` есть описания! Не оставляйте их в виде пустых мест!
Пожалуйста, убедитесь, что за каждой главой следует символ ":" и далее ее описание.
Пожалуйста, создайте одно и только одно описание для каждой главы. 
НЕ разбивайте описания глав на несколько разделов! 
Например, "Глава 1: [описание главы 1]".

тема: {subject}
жанр: {genre}
стиль: {style}
название: {title}
Описание книги: {profile}
Структура книги: {framework}

Пожалуйста, верните список глав и только список глав:
"""

[chapters_ideas]
load_chapters_ideas = false
helper_prompt = """
Составьте список характеристик, которые характеризуют научно-популярное практическое руководство по машинному обучению и искусственному интеллекту для нефтепереработчиков, дающее последовательное понимание как практически реализовать проект машинного обучения, включая последовательную цепочку идей, которые поддерживают основную структуру книги.
Список характеристик:
"""
prompt = """
Вы писатель, и ваша задача - создать основу для одной-единственной главы практического руководства по машинному обучению и искуссвенному интеллекту для специалистов нефтепереработки. 
Вам предоставляется тема, жанр, стиль, название, профиль и основные принципы книги. 
Кроме того, вам предоставляется структура предыдущих глав и общий план книги.
Убедитесь, что вы создали структуру, которая точно описывает идеи и аргументы, изложенные в главе. 
В каждой главе должны быть свои собственные идеи и аргументы, но они должны соответствовать 
другие главы и общая структура книги.
Структура главы должна соответствовать жанру романа.
Структура главы должна соответствовать стилю книги. 

Чтобы написать увлекательную и содержательную книгу, обратите внимание на следующие характеристики:
{features}

тема: {subject}
жанр: {genre}
стиль: {style}
название: {title}
описание книги: {profile}
фреймворк: {framework}

Краткое изложение:
{outline}

Структура главы:
{summaries}

Верните подробную структуру. НЕ ссылайтесь на название главы в структуре!
Верните структуру и только структуру идей и подтверждающих аргументов в главе.
Структура {chapter}:
"""

[ideas]
load_ideas = false
promt = """
Вы пишете практическое руководство по машинному обучению для специалистов нефтепереработки и ваша задача - составить подробный список идей, обсуждаемых в текущей главе книги.
Будьте предельно конкретны в отношении аргументации и особенностей различных идей.
Все идеи описывающие структуру этой главы и аргументы, подтверждающие различные идеи должны быть в строгом порядке. 
Вам предоставляется информация о теме, жанре, стиле, названии, профиле и основных принципах книги, а
также о структуре этой главы.
Кроме того, вам предоставляется список идей, которые были изложены в предыдущих главах.
Список идей должен соответствовать жанру книги.
Список идей должен соответствовать стилю книги.

Каждый элемент этого списка должен отображаться в разных строках. Следуйте этому шаблону:

Идея 1
Идея 2
...
Заключительная идея

тема: {subject}
жанр: {genre}
стиль: {style}
название: {title}
описание книги: {profile}
фреймворк: {framework}

Идеи, которые вы изложили для предыдущих глав: {previous_ideas}

Рамки текущей главы:
{summary}

Не стесняйтесь создавать необходимые идеи для создания значимой структуры.
Возвращайте идеи, и только те идеи, которые укладываются в рамки!
Список идей для этой главы:
"""

[writing]
prompt = """
Вы научно-популярный писатель. Описание книги представлено в виде списка идей. 
Вы уже написали книгу до последней идеи. 
Ваша задача - создать абзацы книги, посвященные новой идее.
Вам будут предоставлены название, структура книги, описание книги и структура текущей главы.
Убедитесь, что абзацы соответствуют структуре главы.
Кроме того, вам будет предоставлен список идей, о которых вы уже писали.
Абзацы должны соответствовать жанру книги.
Абзацы должны соответствовать стилю книги.

Жанр: {genre}
Стиль: {style}
Описание книги: {profile}
Название: {title}
Структура книги: {framework}

Предыдущие идеи: {previous_ideas}
Краткое содержание текущей главы: {summary}
Предыдущие абзацы: {previous_paragraphs}

Новая идея, о которой вам нужно написать прямо сейчас: {current_idea}

Вы являетесь автором и пишете абзацы так, как если бы они были частью книги.
Идея должна быть подкреплена вескими аргументами, проиллюстрирована наглядными примерами и написана простым языком, понятным для читателя. 
Убедитесь, что каждое предложение в каждом абзаце закончено! НЕ оставляйте ни один абзац незаконченным!
Убедитесь, что в каждом абзаце более 6 строк!  
НЕ ссылайтесь на автора или главы в параграфах!
Пишите только те параграфы, которые связаны с этой идеей, с необходимыми аргументами, примерами и соответствующими фактами.
Параграфы книги, описывающие эту идею:
"""
